version: "3"

services:
  app:
    build:
      context: .
    env_file: .env
    container_name: strapi_ELeotronics
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      NODE_VERSION: ${NODE_VERSION}
      YARN_VERSION: ${YARN_VERSION}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: db
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      APP_KEYS: ${APP_KEYS}
      JWT_SECRET: ${JWT_SECRET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_ACCESS_SECRET: ${AWS_ACCESS_SECRET}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_REGION: ${AWS_REGION}
    volumes:
      - ./app:/srv/app
    ports:
      - 1337:1337
    depends_on:
      - db
    networks:
      - strapi

  db:
    image: postgres
    container_name: postgres
    env_file: .env
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    # volumes:
      - ./Backup.sql:/docker-entrypoint-initdb.d/Backup.sql
    ports:
      - 5432:5432
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge