version: '4'

services:
  strapi:
    container_name: strapi
    build: .
    env_file: .env
    image: naskio/strapi
    environment:
      NODE_ENV: ${NODE_ENV}
      NODE_VERSION: ${NODE_VERSION}
      YARN_VERSION: ${YARN_VERSION}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      APP_KEYS: ${APP_KEYS}
      JWT_SECRET: ${JWT_SECRET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_ACCESS_SECRET: ${AWS_ACCESS_SECRET}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_REGION: ${AWS_REGION}
    ports:
      - 1337:1337
    volumes:
      - /home/Strapi/ELeotronicsControle:/srv/app # Nesse caso, copie o projeto para /home/Strapi/
    depends_on:
      - db
    networks:
      - strapi

  db:
    container_name: postgres
    image: postgres
    env_file: .env
    volumes:
      - ./criarDatabase.sql:/docker-entrypoint-initdb.d/criarDatabase.sql
      # - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge